# Generated by Django 4.1 on 2022-08-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LunchToday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompany',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='LunchToday.restaurant'),
        ),
    ]
